import React from 'react';
import { ChevronDown, ChevronUp, ArrowLeft, Heart, Palette, Zap, Smartphone, Shield, Eye, Lock } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import Footer from '@/components/Footer';
import { Link } from 'react-router-dom';
import { usePageMetadata } from "@/hooks/useMetadata";

const FAQ = () => {
  // Custom SEO metadata for FAQ page
  const faqMetadata = {
    title: "FAQ - ColorSnap Color Extraction Tool Questions & Answers",
    description: "Find answers to frequently asked questions about ColorSnap. Learn how to use our color extraction tool, supported formats, privacy features, and get pro tips for best results.",
    keywords: [
      "ColorSnap FAQ",
      "color extraction questions",
      "image color picker help",
      "color palette tool support",
      "design tool questions",
      "color extraction guide",
      "image to color converter",
      "design software FAQ",
      "color picker tool help",
      "web design color tools"
    ],
    openGraph: {
      title: "FAQ - ColorSnap Color Extraction Tool Questions & Answers",
      description: "Find answers to frequently asked questions about ColorSnap. Learn how to use our color extraction tool, supported formats, privacy features, and get pro tips for best results.",
      url: "https://colorsnap.design/faq",
      siteName: "ColorSnap",
      images: [
        {
          url: "https://colorsnap.design/faq-preview.jpg",
          width: 1200,
          height: 630,
          alt: "ColorSnap FAQ - frequently asked questions about color extraction",
          type: "image/jpeg",
        },
      ],
      locale: "en_US",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: "FAQ - ColorSnap Color Extraction Tool Questions & Answers",
      description: "Find answers to frequently asked questions about ColorSnap. Learn how to use our color extraction tool.",
      images: ["https://colorsnap.design/faq-preview.jpg"],
      creator: "@ColorSnapDesign",
      site: "@ColorSnapDesign",
    },
    robots: {
      index: true,
      follow: true,
    },
    alternates: {
      canonical: "https://colorsnap.design/faq"
    }
  };

  usePageMetadata(
    faqMetadata.title,
    faqMetadata.description,
    faqMetadata.openGraph.images[0]?.url
  );

  const faqs = [
    {
      question: "How does ColorSnap work?",
      answer: "ColorSnap uses the ColorThief algorithm to analyze uploaded images and extract the most dominant colors. Simply upload an image and get instant HEX, RGB, and Tailwind CSS color codes that you can copy and use in your projects. The tool processes everything locally in your browser for maximum privacy and speed."
    },
    {
      question: "What file formats does ColorSnap support?",
      answer: "ColorSnap supports all common image formats including JPG, PNG, GIF, WebP, and SVG files. The tool works with any image you can upload to your browser, with a maximum file size of 10MB for optimal performance."
    },
    {
      question: "Is ColorSnap free to use?",
      answer: "Yes, ColorSnap is completely free to use. No registration required, no hidden fees, and your images are processed locally in your browser for privacy. You can use the tool for any project, including commercial work."
    },
    {
      question: "Can I use ColorSnap for commercial projects?",
      answer: "Absolutely! All color palettes generated by ColorSnap are free to use in any project, including commercial work. The tool is designed for professional designers and developers who need reliable color extraction capabilities."
    },
    {
      question: "How many colors does ColorSnap extract?",
      answer: "ColorSnap typically extracts 5-8 dominant colors from your image, depending on the complexity and color distribution. The algorithm identifies the most prominent colors that best represent the overall color scheme of your image."
    },
    {
      question: "What color formats does ColorSnap provide?",
      answer: "ColorSnap provides multiple color formats including HEX, RGB, HSL, CMYK, and LAB. You also get ready-to-use code snippets for Tailwind CSS, CSS variables, Sass variables, JSON, CSV, and Figma tokens."
    },
    {
      question: "Is my data private when using ColorSnap?",
      answer: "Yes, your privacy is our top priority. All image processing happens locally in your browser - your images never leave your device or get uploaded to any server. This ensures complete privacy and security."
    },
    {
      question: "Can I use ColorSnap on mobile devices?",
      answer: "Yes, ColorSnap is fully responsive and works great on mobile devices. The interface adapts to different screen sizes, and you can upload images directly from your mobile device's camera or gallery."
    },
    {
      question: "What's the maximum file size I can upload?",
      answer: "ColorSnap accepts images up to 10MB in size. This limit ensures fast processing and optimal performance. For best results, we recommend using images with good resolution and clear color definition."
    },
    {
      question: "How accurate is the color extraction?",
      answer: "ColorSnap uses the proven ColorThief algorithm which provides highly accurate color extraction. The algorithm analyzes pixel data to identify the most dominant colors, ensuring reliable results for design and development projects."
    },
    {
      question: "Can I save my color palettes?",
      answer: "Currently, ColorSnap processes images in real-time and doesn't store color palettes. However, you can easily copy the color codes and save them in your preferred design tool or document. We're working on adding save functionality in future updates."
    },
    {
      question: "Does ColorSnap work offline?",
      answer: "ColorSnap requires an internet connection to load initially, but once loaded, the color extraction process works entirely in your browser. This means the core functionality works even with limited connectivity."
    }
  ];

  const categories = [
    {
      title: "Getting Started",
      faqs: faqs.slice(0, 3)
    },
    {
      title: "Usage & Features",
      faqs: faqs.slice(3, 7)
    },
    {
      title: "Technical Details",
      faqs: faqs.slice(7, 12)
    }
  ];

  return (
    <>
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100">
        {/* Header */}
        <header className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
          <div className="container mx-auto px-4 py-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <Link to="/" className="flex items-center space-x-3 hover:opacity-80 transition-opacity">
                  <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-xl flex items-center justify-center overflow-hidden">
                    <img 
                      src="/favicon-512x512.webp" 
                      alt="ColorSnap Logo" 
                      className="w-full h-full object-contain"
                    />
                  </div>
                  <div>
                    <h1 className="text-xl sm:text-2xl font-bold text-[#23394a]">
                      ColorSnap
                    </h1>
                    <p className="text-xs sm:text-sm text-[#49a8b0]">
                      Images to Color Palettes
                    </p>
                  </div>
                </Link>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={() => window.history.back()}
                className="text-[#23394a]"
              >
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back
              </Button>
            </div>
          </div>
        </header>

        {/* Hero Section */}
        <section className="container mx-auto px-4 py-8 sm:py-12">
          <div className="text-center max-w-4xl mx-auto mb-12">
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-[#23394a] mb-6">
              Frequently Asked Questions
            </h1>
            <p className="text-lg sm:text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
              Everything you need to know about ColorSnap. Can't find what you're looking for? 
              Feel free to reach out to us.
            </p>
          </div>

          {/* FAQ Categories */}
          <div className="space-y-12">
            {categories.map((category, categoryIndex) => (
              <div key={categoryIndex}>
                <h2 className="text-2xl font-bold text-[#23394a] mb-6 text-center">
                  {category.title}
                </h2>
                <div className="max-w-4xl mx-auto">
                  <Accordion type="single" collapsible className="space-y-4">
                    {category.faqs.map((faq, faqIndex) => (
                      <AccordionItem 
                        key={faqIndex} 
                        value={`item-${categoryIndex}-${faqIndex}`}
                        className="bg-white/80 backdrop-blur-sm rounded-lg border-0 shadow-lg"
                      >
                        <AccordionTrigger className="px-6 py-4 text-left hover:no-underline">
                          <span className="font-medium text-[#23394a]">{faq.question}</span>
                        </AccordionTrigger>
                        <AccordionContent className="px-6 pb-4">
                          <p className="text-gray-600 leading-relaxed">{faq.answer}</p>
                        </AccordionContent>
                      </AccordionItem>
                    ))}
                  </Accordion>
                </div>
              </div>
            ))}
          </div>

          {/* Quick Tips Section */}
          <div className="mt-16">
            <Card className="border-0 shadow-xl bg-gradient-to-r from-[#23394a] to-[#49a8b0] text-white">
              <CardHeader className="text-center">
                <CardTitle className="text-2xl">Pro Tips for Best Results</CardTitle>
                <CardDescription className="text-white/80">
                  Get the most out of ColorSnap with these helpful tips
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  <div className="text-center">
                    <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center mx-auto mb-3">
                      <Palette className="w-6 h-6 text-white" />
                    </div>
                    <h4 className="font-medium mb-2">Use High-Quality Images</h4>
                    <p className="text-sm text-white/80">
                      Clear, well-lit images with distinct colors work best for extraction.
                    </p>
                  </div>
                  <div className="text-center">
                    <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center mx-auto mb-3">
                      <Zap className="w-6 h-6 text-white" />
                    </div>
                    <h4 className="font-medium mb-2">Keep File Sizes Reasonable</h4>
                    <p className="text-sm text-white/80">
                      Images under 5MB process fastest while maintaining quality.
                    </p>
                  </div>
                  <div className="text-center">
                    <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center mx-auto mb-3">
                      <Smartphone className="w-6 h-6 text-white" />
                    </div>
                    <h4 className="font-medium mb-2">Try Different Formats</h4>
                    <p className="text-sm text-white/80">
                      PNG and JPG work great, but WebP offers excellent compression.
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* CTA Section */}
          <div className="text-center mt-12">
            <Card className="border-0 shadow-xl bg-white/80 backdrop-blur-sm">
              <CardContent className="p-8">
                <h3 className="text-2xl font-bold text-[#23394a] mb-4">Ready to Get Started?</h3>
                <p className="text-lg text-gray-600 mb-6">
                  Try ColorSnap now and see how easy it is to extract beautiful color palettes from your images.
                </p>
                <Button
                  size="lg"
                  className="bg-gradient-to-r from-[#f5a94d] to-[#fc6c2c] text-white hover:opacity-90"
                  onClick={() => window.location.href = '/'}
                >
                  Start Extracting Colors
                </Button>
              </CardContent>
            </Card>
          </div>
        </section>

        {/* Footer */}
        <Footer />
      </div>
    </>
  );
};

export default FAQ; 