export const metadata = {
  title: "ColorSnap – Extract Image Color Palette",
  description:
    "Upload an image to extract HEX, RGB, Tailwind CSS, & CSS variables instantly. Free, private, fast color palette tool for designers & developers.",
  keywords: [
    "color picker",
    "color palette generator",
    "extract color from image",
    "image color picker",
    "tailwind css theme generator",
    "hex color extractor",
    "rgb color values",
    "css variables generator",
    "privacy-free design tools",
    "web design color schemes",
    "mobile-friendly color extractor",
    "developer color palette tool",
  ],
  openGraph: {
    title: "ColorSnap – Extract Color Palette from Image",
    description:
      "Get HEX, RGB, and Tailwind CSS themes from any image. Free, private color extraction tool for designers and developers.",
    url: "https://colorsnap.design",
    siteName: "ColorSnap",
    images: [
      {
        url: "https://colorsnap.design/images/og-preview.jpg",
        width: 1200,
        height: 630,
        alt: "ColorSnap color palette extraction tool with vibrant swatches",
        type: "image/jpeg",
      },
      {
        url: "https://colorsnap.design/images/square-og-preview.jpg",
        width: 1200,
        height: 1200,
        alt: "ColorSnap square preview",
        type: "image/png",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "ColorSnap – Extract Color Palette from Image",
    description:
      "Get HEX, RGB, and Tailwind CSS themes from any image. Free and private with ColorSnap.",
    images: ["https://colorsnap.design/images/og-preview.jpg"],
    creator: "@colorsnap",
    site: "@colorsnap",
    domain: "colorsnap.design",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    yandex: "0d5dbc3686e82fee",
  },
  alternates: {
    canonical: "https://colorsnap.design",
  },
  authors: [{ name: "ColorSnap" }],
  creator: "ColorSnap",
  publisher: "ColorSnap",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("https://colorsnap.design"),
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
    other: [
      { rel: "icon", url: "/favicon-32x32.png", sizes: "32x32" },
      { rel: "icon", url: "/favicon-192x192.png", sizes: "192x192" },
    ],
  },
  manifest: "/site.webmanifest",
  themeColor: "#23394a",
  colorScheme: "light",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
  applicationName: "ColorSnap",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "ColorSnap",
  },
  other: {
    "msapplication-TileColor": "#23394a",
    "msapplication-config": "/browserconfig.xml",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
    "apple-mobile-web-app-title": "ColorSnap",
    "mobile-web-app-capable": "yes",
    "format-detection": "telephone=no",
    "msapplication-tap-highlight": "no",
  },
  category: "Design Tools",
  classification: "Web Application",
  referrer: "origin-when-cross-origin",
};