export const metadata = {
  title: "Extract Color Palette from Image – ColorSnap",
  description:
    "Upload image to get HEX, RGB, Tailwind CSS theme & CSS variables instantly. Free, private, and fast color palette generator tool for designers and developers.",
  keywords: [
    "extract color from image",
    "image color picker",
    "color palette generator",
    "tailwind css theme",
    "get hex from image",
    "rgb color extractor",
    "css variables from image colors",
    "color extraction tool",
    "design color palette",
    "web design colors",
    "color scheme generator",
    "image to colors",
    "color picker tool",
    "hex color codes",
    "rgb color values",
    "color palette",
    "color extractor",
    "image colors",
    "HEX codes",
    "RGB values",
    "Tailwind CSS",
    "color picker",
    "design tools",
    "web design",
    "color scheme generator",
    "free tool",
    "browser-based",
    "privacy-first",
    "free color palette tool",
    "color palette generator for designers",
    "best color palette tool",
    "color extraction for developers"
  ],
  openGraph: {
    title: "ColorSnap – Extract Color Palette from Image",
    description:
      "Get HEX, RGB, and Tailwind CSS themes from any image. Generate color palettes instantly with ColorSnap. Free online color extraction tool for designers and developers.",
    url: "https://colorsnap.design",
    siteName: "ColorSnap",
    images: [
      {
        url: "https://colorsnap.design/preview.jpg",
        width: 1200,
        height: 630,
        alt: "ColorSnap - Color palette extraction tool showing vibrant color swatches and HEX codes",
        type: "image/jpeg",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "ColorSnap – Extract Color Palette from Image",
    description:
      "Get HEX, RGB, and Tailwind CSS themes from any image. Generate color palettes instantly with ColorSnap.",
    images: ["https://colorsnap.design/preview.jpg"],
    creator: "@colorsnap",
    site: "@colorsnap",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "your-google-verification-code",
    yandex: "your-yandex-verification-code",
    yahoo: "your-yahoo-verification-code",
    bing: "REPLACE_WITH_BING_WEBMASTER_TOOLS_VERIFICATION_CODE",
  },
  alternates: {
    canonical: "https://colorsnap.design",
  },
  authors: [{ name: "ColorSnap" }],
  creator: "ColorSnap",
  publisher: "ColorSnap",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("https://colorsnap.design"),
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  themeColor: "#23394a",
  colorScheme: "light",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
  applicationName: "ColorSnap",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "ColorSnap",
  },
  other: {
    "msapplication-TileColor": "#23394a",
    "msapplication-config": "/browserconfig.xml",
    "theme-color": "#23394a",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
    "apple-mobile-web-app-title": "ColorSnap",
    "mobile-web-app-capable": "yes",
    "format-detection": "telephone=no",
    "msapplication-tap-highlight": "no",
  },
  category: "Design Tools",
  classification: "Web Application",
  referrer: "origin-when-cross-origin",
};
